### ISSUE TITLE
service: carbu_com.get_lowest_fuel_price

### ISSUE THREAD

**Issue by mupsje** [myTselection/Carbu_com#38]
Hello, great job.
before this I scraped the sites also.

Quick Q:

I noticed that the service: carbu_com.get_lowest_fuel_price
is only working for BE?
because I only get data when i use like.

```
service: carbu_com.get_lowest_fuel_price
data: 
  fuel_type: diesel
  country: BE
  postalcode: 3620
  max_distance: 10
```
if I do

```
service: carbu_com.get_lowest_fuel_price
data: 
  fuel_type: diesel
  country: NL
  postalcode: 6051 JR
  max_distance: 10
```

I get errors

thanks for the answer ;)
