### ISSUE TITLE
carbu_com.get_lowest_fuel_price_coor Broken?

### ISSUE THREAD

**Issue by skank01** [myTselection/Carbu_com#59]
I dont get any outpute when used...
Is it still broken?

**Comment by myTselection** [comment]
Event is triggered, see readme which has full example of usage.

**Comment by skank01** [comment]
Hi

I always get an error or no response
![image](https://github.com/user-attachments/assets/ffc5c52e-0adf-48f6-86c4-da5d4bdc9871)

**Comment by myTselection** [comment]
The from - to parameters are required when searching for a station in between two location. Then the action/service `carbu_com.get_lowest_fuel_price_on_route` or `carbu_com.get_lowest_fuel_price_on_route_coor` should be used.
The action you are using requires other parameters, see below. In the developer page you can test services/actions and example parameters with info are shown.


```

action: carbu_com.get_lowest_fuel_price_coor
data:
  fuel_type: diesel
  latitude: 50.8503
  longitude: 4.3517
  max_distance: 5
  filter: Shell


```

**Comment by myTselection** [comment]
hmm, I now see your second screenshot is using the correct action/service. I'll further check this

**Comment by myTselection** [comment]
Are you sure a valid GEO_API_KEY is set? I've added some validation in R11.2.4 to throw an ServiceValidationError if services are used that require a valid GEO_API_KEY while not set.

**Comment by skank01** [comment]
Oops; its still GEO_API_KEY

**Comment by skank01** [comment]
I added api key, error is gone now and it is triggering, however i dont get any notification

**Comment by myTselection** [comment]
did you setup an automation to trigger on the specific event? see example code on the reamde

**Comment by skank01** [comment]
I didnt set up an automation, i tried it first using development tools ... using the code from the readme and it doesnt work,.
The other does work ! (carbu_com.get_lowest_fuel_price_on_route)

**Comment by myTselection** [comment]
the issue isn't clear to me. Which part is not working? If you don't setup an automation to trigger based on the event, no notification will be shown. 
So before testing using the development tools, you'll need to setup an automation to show a notification.
if that's not the issue, you'll need to share some more details or screenshot
```
alias: Carbu event
description: ""
trigger:
  - platform: event
    event_type: carbu_com_lowest_fuel_price # or carbu_com_lowest_fuel_price_coor
condition: []
action:
  - service: notify.persistent_notification
    data:
      message: >-
        {{ trigger.event.data.supplier_brand }}: {{ trigger.event.data.price }}€
        at {{ trigger.event.data.distance }}km, {{ trigger.event.data.address }}
mode: single
```
